[tool.black]
line-length = 88  # Adjust this to your preferred line length
exclude = '\.git|\.hg|\.mypy_cache|\.tox|venv|\.venv|_build|buck-out|build|dist|migrations|node_modules|\.nox|\.svn|\.vscode|\.idea'