# Generated by Django 4.2.5 on 2023-09-24 10:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="sensor_vehi_name_493f8c_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=-90.0),
                            django.core.validators.MaxValueValidator(limit_value=90.0),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=-180.0
                            ),
                            django.core.validators.MaxValueValidator(limit_value=180.0),
                        ]
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("vehicle_speed", models.FloatField()),
                ("speed_limit", models.FloatField()),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="sensor.vehicle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude"], name="sensor_sens_latitud_c6e4a4_idx"
                    ),
                    models.Index(
                        fields=["longitude"], name="sensor_sens_longitu_e35271_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="sensor_sens_timesta_d8547a_idx"
                    ),
                ],
            },
        ),
    ]
